-- Paste these entries inside ox_inventory/data/items.lua (inside the return { ... } table).
-- Then copy install/ox_inventory_images/*.png into ox_inventory/web/images/

	['chameleonpaint_161'] = {
		label = '#161 Monochrome Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #161. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_161.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_162'] = {
		label = '#162 Night & Day Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #162. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_162.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_163'] = {
		label = '#163 The Verlierer Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #163. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_163.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_164'] = {
		label = '#164 Sprunk Extreme Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #164. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_164.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_165'] = {
		label = '#165 Vice City Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #165. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_165.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_166'] = {
		label = '#166 Synthwave Nights Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #166. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_166.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_167'] = {
		label = '#167 Four Seasons Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #167. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_167.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_168'] = {
		label = '#168 Maisonette 9 Throwback Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #168. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_168.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_169'] = {
		label = '#169 Bubblegum Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #169. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_169.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_170'] = {
		label = '#170 Full Rainbow Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #170. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_170.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_171'] = {
		label = '#171 Sunset Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #171. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_171.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_172'] = {
		label = '#172 The Seven Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #172. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_172.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_173'] = {
		label = '#173 Kamen Rider Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #173. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_173.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_174'] = {
		label = '#174 Chromatic Aberration Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #174. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_174.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_175'] = {
		label = '#175 Its Christmas! Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #175. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_175.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},
	['chameleonpaint_176'] = {
		label = '#176 Temperature Spray',
		weight = 1,
		stack = true,
		close = true,
		consume = 0,
		description = 'Chameleon spray #176. Use in a vehicle to paint it. Paint is saved.',
		client = {
			image = 'chameleonpaint_176.png',
			export = 'djfivem-spraypaint.chameleonpaint',
		},
	},

